# Generated by Django 3.1.5 on 2021-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210107_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateQuiz',
            new_name='Quiz',
        ),
        migrations.RenameModel(
            old_name='CreateQuizQuestion',
            new_name='QuizQuestion',
        ),
    ]
