# Generated by Django 3.1.5 on 2021-01-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20210107_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Quesiton')),
                ('selected_answer', models.CharField(max_length=100, verbose_name='Selected answer')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Correct answer')),
                ('time_taken', models.CharField(max_length=100, verbose_name='Time Taken to complete the test')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Student's Score",
                'verbose_name_plural': "Student's Score",
            },
        ),
    ]
