# Generated by Django 3.1.5 on 2021-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='marks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marks'),
        ),
    ]
