# Generated by Django 3.1.5 on 2021-01-08 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20210108_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_attempts_record',
            new_name='StudenAttemptRecord',
        ),
    ]
